/*
  Vendor the site's web fonts so visitors never touch Google's CDN.

  Downloads the exact css2 stylesheet Base.astro used to hot-link (for the
  ACTIVE pairing in site.json + the constant Caveat accent), pulls every
  woff2 it references into public/fonts/, and rewrites the CSS to local
  paths (public/fonts/fonts.css). Base.astro inlines that CSS when it
  exists — removing the render-blocking third-party stylesheet + the
  fonts.gstatic.com connection from every page load.

  Keep-last-good: any failure leaves the previously committed fonts in
  place and exits 0 — a font refresh must never break a deploy. Run by
  deploy.yml before the housekeeping commit; safe to run locally too.
*/
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fontPairings, googleCssUrl } from '../src/data/font-pairings.mjs';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT_DIR = path.join(ROOT, 'public/fonts');
const site = JSON.parse(fs.readFileSync(path.join(ROOT, 'src/data/site.json'), 'utf8'));

const pairing = fontPairings[site.fontPairing] || fontPairings.fraunces;
const cssUrl = googleCssUrl(pairing);

// A modern-Chrome UA gets the woff2 + unicode-range subset stylesheet
// (the default UA is served legacy TTFs, several MB heavier).
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

try {
  const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`css2 fetch ${res.status}`);
  let css = await res.text();

  const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+/g) || [])];
  if (!urls.length) throw new Error('no font URLs in stylesheet');

  const files = new Map(); // remote URL -> local filename
  for (const u of urls) {
    // Deterministic name: family path fragment + short content-address of
    // the URL, so a pairing change swaps files cleanly and never collides.
    const hash = crypto.createHash('sha1').update(u).digest('hex').slice(0, 10);
    const family = (u.match(/\/s\/([a-z0-9]+)\//i) || [, 'font'])[1];
    files.set(u, `${family}-${hash}.woff2`);
  }

  const downloads = await Promise.all(
    [...files].map(async ([u, name]) => {
      const r = await fetch(u, { headers: { 'User-Agent': UA } });
      if (!r.ok) throw new Error(`font fetch ${r.status}: ${u}`);
      return [name, Buffer.from(await r.arrayBuffer())];
    })
  );

  // All fetches succeeded — now (and only now) replace the directory.
  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });
  for (const [name, buf] of downloads) fs.writeFileSync(path.join(OUT_DIR, name), buf);
  for (const [u, name] of files) css = css.replaceAll(u, `/fonts/${name}`);
  fs.writeFileSync(
    path.join(OUT_DIR, 'fonts.css'),
    `/* generated by scripts/vendor-fonts.mjs — do not edit (source: ${cssUrl}) */\n${css}`
  );
  console.log(`vendored ${files.size} font files for pairing "${site.fontPairing || 'fraunces'}"`);
} catch (err) {
  console.warn(`vendor-fonts: keeping last-good fonts (${err.message})`);
}
